language: java

install:
  - TERM=dumb gradle -q assemble

script:
  - TERM=dumb gradle check

jdk:
  - oraclejdk7
  - openjdk7

services: mysql

before_script:
  - mysql -e 'create database jdbctest;'
